### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by jHoyne** [monners/Card-Deck#2]
Are there any restrictions to using this? I would like to use it on a project I'm working on.

**Comment by monners** [comment]
Nope, no restrictions.  Go nuts.

Would love to see what you end up using it for.

**Comment by jHoyne** [comment]
Thanks k.

On 15 June 2015 at 16:35, Josh Moncrieff <notifications@github.com> wrote:

> Nope, no restrictions. Go nuts.
>
> Would love to see what you end up using it for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monners/Card-Deck/issues/2#issuecomment-112218224>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>
